server:
  port: 82
spring:
  application:
    name: cloud-comsumer-fegin

#Eureka 配置 用于注册服务
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
feign:
  hystrix:
    enabled: true  #开启服务降级模式

