server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/clouddb01?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  application:
    name: cloud-provider-01
mybatis:
  type-aliases-package: com.xiaobai.clouprovider.entity
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
   com.xiaobai.clouprovider: debug