server:
  port: 1202
spring:
  application:
    name: cloud-gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ # 集群配置的Eureka注册（若是单一就写一个）
  instance:
    instance-id: cloud-gateway-zuul-1202
    prefer-ip-address: true
zuul:
  ignored-services: "*" #不允许使用服务名访问
  routes:
    dept:
      path: /dept/**
      serviceId: cloud-comsumer-fegin  #将外部请求转发到cloud-consumer-fegin 上
  host:  #设置超时时间 如果不设置  会导致访问失败
    connect-timeout-millis: 4000
    socket-timeout-millis: 4000
ribbon: #设置超时时间  要比 zuul 的大
  ConnectTimeout: 5000
  ReadTimeout: 5000



